-- =====================================================
-- PART 1 — CORE KPI & FUNNEL ANALYSIS
-- =====================================================

-- PART OVERVIEW:
-- This section focuses on marketing funnel analytics,
-- campaign effectiveness, customer acquisition,
-- and KPI-based business reporting using SQL.

-- =====================================================
-- CONCEPT 1 — MARKETING CHANNEL PERFORMANCE
-- =====================================================

-- CONCEPT OVERVIEW:
-- Analyze marketing channels based on spending,
-- conversions, and customer acquisition performance.

-- =====================================================
-- QUERY 1 — HIGHEST SPENDING CHANNEL
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify which marketing
-- channels consume the highest marketing budget.

-- OBJECTIVE:
-- Analyze total spending across marketing channels.

SELECT
    channel,
    SUM(spend_amount) AS total_spending
FROM marketing_spend
GROUP BY channel
ORDER BY total_spending DESC
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report identifies the marketing channel
-- receiving the highest investment. Businesses
-- can evaluate whether higher spending channels
-- are generating sufficient customer engagement
-- and conversion performance.

-- =====================================================
-- QUERY 2 — HIGHEST CONVERSION CHANNEL
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify channels generating
-- the highest customer conversions.

-- OBJECTIVE:
-- Analyze total conversions generated by
-- different marketing channels.

SELECT
    channel,
    SUM(conversions) AS total_conversion
FROM marketing_spend
GROUP BY channel
ORDER BY total_conversion DESC
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report highlights channels generating
-- the highest customer conversions, helping
-- businesses optimize marketing investment
-- and customer acquisition strategy.

-- =====================================================
-- CONCEPT 2 — FUNNEL CONVERSION ANALYTICS
-- =====================================================

-- CONCEPT OVERVIEW:
-- Analyze customer funnel efficiency using
-- conversion rate and campaign performance KPIs.

-- =====================================================
-- QUERY 1 — CHANNEL-WISE CONVERSION RATE
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify channels with
-- the strongest customer conversion performance.

-- OBJECTIVE:
-- Measure conversion rate across
-- different marketing channels.

SELECT
    channel,
    SUM(clicks) AS total_clicks,
    SUM(conversions) AS total_conversions,

    ROUND(
        (SUM(conversions)/NULLIF(SUM(clicks),0))*100,2
    ) AS conversion_rate

FROM marketing_spend
GROUP BY channel
ORDER BY conversion_rate DESC
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report identifies channels with the
-- highest conversion efficiency. Businesses
-- can focus on high-performing channels
-- to improve marketing ROI and customer acquisition.

-- =====================================================
-- QUERY 2 — FUNNEL EFFICIENCY RANKING
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to compare funnel efficiency
-- across marketing channels.

-- OBJECTIVE:
-- Rank channels based on impressions,
-- conversions, and conversion efficiency.

WITH temp AS(
SELECT
    channel,
    SUM(impressions) AS total_impressions,
    SUM(conversions) AS total_converted,

    ROUND(
        (SUM(conversions)/NULLIF(SUM(impressions),0))*100,2
    ) AS conversion_rate

FROM marketing_spend
GROUP BY channel
)

SELECT *
FROM temp
ORDER BY total_impressions DESC,
         conversion_rate ASC
LIMIT 3;

-- BUSINESS INTERPRETATION:
-- The report compares funnel efficiency
-- across channels and identifies areas
-- requiring improvement in customer conversion.

-- =====================================================
-- CONCEPT 3 — REGIONAL CAMPAIGN PERFORMANCE
-- =====================================================

-- CONCEPT OVERVIEW:
-- Analyze regional marketing performance
-- using impressions, clicks, and conversions.

-- =====================================================
-- QUERY 1 — REGIONAL CLICK THROUGH RATE (CTR)
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify regions
-- generating stronger customer engagement.

-- OBJECTIVE:
-- Measure regional click-through rate (CTR)
-- performance.

SELECT
    region,
    SUM(impressions) AS total_impressions,
    SUM(clicks) AS total_clicks,

    ROUND(
        (SUM(clicks)/NULLIF(SUM(impressions),0))*100,2
    ) AS click_rate

FROM marketing_spend
GROUP BY region
ORDER BY click_rate DESC
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report identifies regions generating
-- the highest customer engagement and ad interaction.

-- =====================================================
-- QUERY 2 — REGIONAL COST PER CONVERSION
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to measure regional
-- customer acquisition efficiency.

-- OBJECTIVE:
-- Analyze cost per conversion across regions.

SELECT
    region,
    SUM(spend_amount) AS total_spending,
    SUM(conversions) AS total_conversions,
    ROUND(
        (SUM(spend_amount)/NULLIF(SUM(conversions),0)),2
    ) AS cost_per_conversion
FROM marketing_spend
GROUP BY region
ORDER BY cost_per_conversion
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report identifies regions with
-- the most cost-efficient customer conversions,
-- helping businesses optimize regional marketing budgets.

-- =====================================================
-- CONCEPT 4 — MARKETING ROI & EFFICIENCY
-- =====================================================

-- CONCEPT OVERVIEW:
-- Analyze marketing ROI and customer acquisition efficiency.

-- =====================================================
-- QUERY 1 — CONVERSION PER DOLLAR
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to evaluate return
-- generated from marketing investment.

-- OBJECTIVE:
-- Measure customer conversions generated
-- per dollar spent.

SELECT
    channel,
    SUM(spend_amount) AS total_spending,
    SUM(conversions) AS total_conversions,
    ROUND(
        (SUM(conversions)/NULLIF(SUM(spend_amount),0)),2
    ) AS conv_per_dollar
FROM marketing_spend
GROUP BY channel
ORDER BY conv_per_dollar DESC
LIMIT 3;

-- BUSINESS INTERPRETATION:
-- The report identifies channels generating
-- the highest conversion efficiency per dollar spent.

-- =====================================================
-- QUERY 2 — CUSTOMER ACQUISITION EFFICIENCY
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify channels
-- generating customers efficiently.

-- OBJECTIVE:
-- Analyze customer acquisition efficiency
-- across marketing channels.

SELECT
    channel,
    SUM(spend_amount) AS total_spending,
    SUM(new_customers) AS total_new_customers,
    ROUND(
        (SUM(new_customers)/NULLIF(SUM(spend_amount),0))*100,2
    ) AS dollar_per_customer
FROM marketing_spend
GROUP BY channel
ORDER BY dollar_per_customer DESC
LIMIT 1;

-- BUSINESS INTERPRETATION:
-- The report identifies channels generating
-- higher customer acquisition efficiency
-- with optimized marketing spending.

-- =====================================================
-- CONCEPT 5 — CAMPAIGN PERFORMANCE SEGMENTATION
-- =====================================================

-- CONCEPT OVERVIEW:
-- Classify marketing campaigns based on
-- conversion performance and campaign efficiency.

-- =====================================================
-- QUERY 1 — CAMPAIGN PERFORMANCE CLASSIFICATION
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify high-performing
-- and low-performing marketing campaigns.

-- OBJECTIVE:
-- Classify marketing channels based on
-- conversion rate performance.

WITH temp AS(
SELECT
    channel,
    SUM(conversions) AS total_conversions,
    SUM(clicks) AS total_clicks,
    ROUND(
        (SUM(conversions)/NULLIF(SUM(clicks),0))*100,2
    ) AS conversion_rate

FROM marketing_spend
GROUP BY channel
)
SELECT *,
CASE
    WHEN conversion_rate >= 5
    THEN 'High Performing'
    WHEN conversion_rate < 2
    THEN 'Low Performing'
    ELSE 'Average Performing'
END AS performance

FROM temp;

-- BUSINESS INTERPRETATION:
-- The report classifies marketing channels
-- based on conversion efficiency and helps
-- businesses identify strong and weak campaigns.

-- =====================================================
-- QUERY 2 — HIGH PERFORMING CAMPAIGN DETECTION
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify campaigns
-- generating strong conversion performance.

-- OBJECTIVE:
-- Detect high-performing marketing campaigns
-- using conversion rate thresholds.

WITH temp AS(
SELECT
    channel,
    SUM(clicks) AS total_clicks,
    SUM(conversions) AS total_conversions,
    ROUND(
        (SUM(conversions)/NULLIF(SUM(clicks),0))*100,2
    ) AS conversion_rate

FROM marketing_spend
GROUP BY channel
HAVING conversion_rate > 4
)
SELECT *,
CASE
    WHEN conversion_rate > 6
    THEN 'Excellent'

    ELSE 'Good'
END AS performance
FROM temp;

-- BUSINESS INTERPRETATION:
-- The report identifies high-performing
-- campaigns generating strong conversion rates.
-- Businesses can increase investment in
-- these campaigns to maximize customer acquisition.

-- =====================================================
-- CONCEPT 6 — TREND & GROWTH ANALYSIS
-- =====================================================

-- CONCEPT OVERVIEW:
-- Analyze marketing spending trends
-- and campaign growth performance over time.

-- =====================================================
-- QUERY 1 — RUNNING MARKETING SPEND TREND
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to monitor marketing
-- spending growth over time.

-- OBJECTIVE:
-- Analyze cumulative marketing spending trends
-- across different months.

WITH temp AS(
SELECT
    month,
    SUM(spend_amount) AS total_spending
FROM marketing_spend
GROUP BY month
)
SELECT *,
SUM(total_spending)
OVER(ORDER BY month) AS running_total
FROM temp;

-- BUSINESS INTERPRETATION:
-- The report tracks cumulative marketing spending
-- over time and helps businesses monitor
-- campaign investment growth trends.

-- =====================================================
-- QUERY 2 — CONVERSION TREND DASHBOARD
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify conversion
-- performance trends across marketing channels.

-- OBJECTIVE:
-- Analyze impressions, clicks, conversions,
-- and overall conversion trends.

SELECT
    channel,
    SUM(impressions) AS total_impressions,
    SUM(clicks) AS total_clicks,
    SUM(conversions) AS total_conversions,
    ROUND(
        (SUM(conversions)/NULLIF(SUM(impressions),0))*100,2
    ) AS conversion_rate

FROM marketing_spend
GROUP BY channel
ORDER BY conversion_rate DESC
LIMIT 3;

-- BUSINESS INTERPRETATION:
-- The report identifies marketing channels
-- generating strong customer engagement
-- and conversion performance across the funnel.

-- =====================================================
-- PART 1 COMPLETED
-- =====================================================
