-- =====================================================
-- PART 3 — BUSINESS DASHBOARD & STRATEGIC ANALYTICS
-- =====================================================

-- PART OVERVIEW:
-- This section focuses on advanced business reporting,
-- dashboard analytics, customer retention analysis,
-- cohort analysis, churn analytics,
-- and executive KPI reporting using SQL.

-- KEY BUSINESS AREAS COVERED:
-- • Cohort Analysis
-- • Customer Retention Analytics
-- • Churn Analysis
-- • Executive KPI Dashboards
-- • Revenue Growth Reporting
-- • Product Performance Analytics
-- • Regional Performance Analysis
-- • Customer Activity Segmentation
-- • Business Strategy Reporting

-- SQL CONCEPTS USED:
-- • CTEs
-- • Window Functions
-- • DENSE_RANK()
-- • LAG()
-- • CASE WHEN
-- • DATE Functions
-- • Aggregations
-- • GROUP BY
-- • KPI Dashboards
-- • CRM Analytics
-- • Cohort Analytics
-- • Strategic Business Reporting

-- =====================================================

-- ===================================== 
-- COHORT REVENUE PERFORMANCE ANALYSIS
-- ===================================== 

-- ===========
-- -- QUERY 1:
-- ===========

-- OBJECTIVE:
-- Analyze acquisition cohorts based on acquisition month.
-- Measure total customers, total orders, and total revenue
-- generated by each acquisition cohort.

SELECT
    c.acquisition_month,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    COUNT(o.order_id) AS total_orders,
    SUM(o.revenue) AS total_revenue
FROM customers c
INNER JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.acquisition_month
ORDER BY total_revenue DESC;

-- BUSINESS INTERPRETATION:
-- In the given output, we can observe strong customer
-- acquisition volume across multiple acquisition months,
-- with several cohorts generating very high total revenue
-- and order volume.
--
-- The March-21 cohort generated the highest revenue and
-- total orders, indicating that this acquisition period
-- performed exceptionally well.
--
-- Businesses can use this insight to strategically increase
-- marketing investment, targeted advertisements, and seasonal
-- promotional campaigns during high-performing acquisition
-- periods to maximize customer conversion and revenue.

-- ===========
-- -- QUERY 2:
-- ===========

-- OBJECTIVE:
-- Analyze customer acquisition cohorts including customers
-- who did not place any orders using LEFT JOIN.
-- Identify cohorts with weak customer conversion and
-- low purchasing activity.

SELECT
    c.acquisition_month,
    COUNT(DISTINCT c.customer_id) AS total_customers,
    COUNT(o.order_id) AS total_orders,
    SUM(o.revenue) AS total_revenue
FROM customers c
LEFT JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.acquisition_month
ORDER BY total_revenue DESC;

-- BUSINESS INTERPRETATION:
-- In the given output, we can observe that some acquisition
-- cohorts contain a large number of customers but generated
-- very low or zero order activity.
--
-- This may indicate low customer conversion rates, weak
-- customer engagement, or customer drop-offs after acquisition.
--
-- Businesses can use this insight to improve onboarding,
-- customer engagement strategies, personalized marketing,
-- and targeted conversion campaigns to convert acquired
-- users into paying customers.
--
-- The analysis also highlights a possible customer ID
-- inconsistency between acquisition and transactional systems,
-- which reflects a common real-world business data challenge.

-- =====================================================
-- COHORT REVENUE PERFORMANCE ANALYSIS
-- =====================================================

-- ===========
-- -- QUERY 1:
-- ===========

-- OBJECTIVE:
-- Analyze customer acquisition cohorts based on
-- acquisition month and measure total customers,
-- total orders, and total revenue generated by
-- each acquisition cohort.
WITH temp AS(
SELECT
  customer_id,
  COUNT(order_id) AS total_orders,
  SUM(revenue) AS total_revenue,
  ROUND((SUM(revenue)/NULLIF(COUNT(order_id),0)),2
  )AS avg_order_value
FROM orders
GROUP BY customer_id
ORDER BY total_orders
)
SELECT *,
   CASE
     WHEN total_orders>9 THEN 'Loyal'
     WHEN total_orders>4 THEN 'Moderate'
     ELSE 'One time'
   END AS cust_segment
FROM temp;
-- BUSINESS INTERPRETATION:
-- In the given output, we can observe strong
-- customer acquisition volume across multiple
-- acquisition months, with several cohorts
-- generating high order volume and revenue.
--
-- The March-21 cohort generated the highest
-- revenue and total orders, indicating that
-- this acquisition period performed exceptionally
-- well.
--
-- Businesses can use this insight to strategically
-- increase marketing investment, targeted
-- advertisements, and seasonal promotional
-- campaigns during high-performing acquisition
-- periods to maximize customer conversion and
-- revenue generation.

-- ===========
-- -- QUERY 2:
-- ===========

-- OBJECTIVE:
-- Analyze customer acquisition cohorts including
-- customers who did not place any orders using
-- LEFT JOIN to identify weak customer conversion
-- and low purchasing activity.
WITH temp AS(
  SELECT
    customer_id,
    COUNT(order_date) AS total_orders,
    SUM(revenue) AS total_revenue,
    ROUND((SUM(revenue)/NULLIF(COUNT(order_id),0)),2
    ) AS avg_order_value
  FROM orders
  GROUP BY customer_id
)
SELECT *,
  DENSE_RANK() OVER(ORDER BY total_orders DESC) AS cust_rank
FROM temp;
-- BUSINESS INTERPRETATION:
-- In the given output, we can observe that some
-- acquisition cohorts contain a large number of
-- customers but generated very low or zero order
-- activity.
--
-- This may indicate low customer conversion rates,
-- weak customer engagement, customer drop-offs
-- after acquisition, or customer ID inconsistencies
-- between acquisition and transactional systems.
--
-- Businesses can use this insight to improve
-- onboarding strategies, customer engagement,
-- personalized marketing campaigns, and conversion
-- optimization programs to convert acquired users
-- into active paying customers.

-- =====================================================
-- Churn & Customer Activity Analysis
-- =====================================================

-- ===========
-- -- QUERY 1:
-- ===========

-- OBJECTIVE:
-- Identify customer inactivity and classify customers
-- into Active, At Risk, and Churned segments.
WITH temp AS(
SELECT
  customer_id,
  MAX(order_date) AS last_order_date,
  DATEDIFF(CURDATE(),MAX(order_date)) AS days_since_last_order
FROM orders
GROUP BY customer_id
)
SELECT *,
  CASE
    WHEN days_since_last_order>180 THEN 'churned'
    WHEN days_since_last_order>90  THEN 'At Risk'
    ELSE 'Active' 
  END AS activity_status
FROM temp;
-- BUSINESS INTERPRETATION:
-- Most customers fall under the Churned category,
-- indicating low recent customer activity and weak retention.
-- Businesses can use retention campaigns, personalized offers,
-- and loyalty programs to reduce customer churn.

-- ===========
-- -- QUERY 2:
-- ===========

-- OBJECTIVE:
-- Segment customers based on revenue contribution,
-- order frequency, and inactivity period to identify
-- high-value churn-risk and low-engagement customers.
WITH temp AS(
  SELECT
    customer_id,
    SUM(revenue) AS total_revenue,
    COUNT(order_date) AS total_orders,
    MAX(order_date) AS last_order_date,
    DATEDIFF(CURDATE(),MAX(order_date)) AS days_since_last_order
FROM orders
GROUP BY customer_id
)
SELECt *,
  CASE
    WHEN days_since_last_order>180 AND total_revenue>50000 THEN 'High Value Churn Risk'
    WHEN days_since_last_order>60 AND total_revenue>20000 THEN 'Medium Value AND Risk'
    WHEN days_since_last_order<=60 THEN 'Active Customer'
    WHEN total_orders<10 THEN 'Low Engagement'
  END AS activity_status
FROM temp;
-- BUSINESS INTERPRETATION:
-- Many customers belong to the Low Engagement category,
-- while several customers fall under High Value Churn Risk.
-- Businesses can target these customers using personalized
-- retention strategies, exclusive offers, and reactivation campaigns.

-- =====================================================
-- Executive KPI Dashboard & Business Reporting
-- =====================================================

-- ===========
-- -- QUERY 1:
-- ===========

-- =====================================================
-- EXECUTIVE KPI DASHBOARD
-- =====================================================

-- BUSINESS PROBLEM:
-- Business stakeholders need a centralized KPI dashboard
-- to monitor overall customer activity, revenue performance,
-- and repeat customer behavior for strategic decision-making.

-- OBJECTIVE:
-- Create an executive-level KPI dashboard summarizing
-- overall business performance, customer retention,
WITH temp AS(
SELECT
  SUM(revenue) AS total_revenue,
  COUNT(order_id) AS total_orders,
  COUNT(DISTINCT customer_id)AS total_customers,
  ROUND(SUM(revenue)/NULLIF(COUNT(order_id),0),2) AS avg_order_value,
  ROUND(SUM(revenue)/NULLIF(COUNT(DISTINCT customer_id),0),2) AS avg_customer_revenue,
  COUNT(DISTINCT CASE
        WHEN customer_id IN (
            SELECT customer_id
            FROM orders
            GROUP BY customer_id
            HAVING COUNT(order_id) > 1
        )
        THEN customer_id
    END) AS repeat_customers
FROM orders
)
SELECT *,
   ROUND((repeat_customers/NULLIF(total_customers,0))*100,2) AS repeat_customer_pct
FROM temp;
-- BUSINESS INTERPRETATION:
-- The dashboard provides a high-level overview of
-- overall business performance including total customers,
-- total orders, total revenue, average order value,
-- and repeat customer percentage.
--
-- A strong repeat customer percentage indicates healthy
-- customer retention and customer engagement performance.
--
-- Businesses can use this dashboard to monitor revenue growth,
-- evaluate customer retention strength, and improve strategic
-- decision-making through targeted marketing and loyalty programs.

-- ===========
-- -- QUERY 2:
-- ===========

-- OBJECTIVE:
-- Analyze monthly revenue performance and
-- measure month-over-month revenue growth trends.
WITH temp AS(
SELECT
  DATE_FORMAT(order_date,'%Y %m') AS month_,
  COUNT(order_date) AS total_orders,
  COUNT(DISTINCT customer_id)AS total_customers,
  SUM(revenue) AS monthly_revenue,
  ROUND((SUM(revenue)/NULLIF(COUNT(order_id),0)),2) AS avg_order_value
FROM orders
GROUP BY DATE_FORMAT(order_date,'%Y %m')
),
prev_month AS(
SELECT *,
  LAG(monthly_revenue) OVER(ORDER BY month_) AS prev_month_revenue
FROM temp
)
SELECT *,
  ROUND(
        ((monthly_revenue-prev_month_revenue)
        /NULLIF(prev_month_revenue,0))*100,2
        ) AS revenue_growth_percentage
FROM prev_month;
-- BUSINESS INTERPRETATION:
-- The report shows strong positive monthly revenue growth
-- and increasing customer activity across multiple periods.
-- Businesses can use this analysis to identify
-- high-performing months and optimize seasonal
-- marketing and promotional strategies.

-- ========
-- Query 3:Regional Performance Dashboard
-- ========

-- OBJECTIVE:
-- Analyze regional business performance based on
-- customers, orders, revenue, and revenue contribution percentage.
WITH temp AS(
 SELECT
  c.region,
  COUNT(o.order_id) AS total_orders,
  COUNT(DISTINCT c.customer_id) AS total_customers,
  SUM(o.revenue) AS total_revenue,
  ROUND((SUM(o.revenue)/NULLIF(COUNT(o.order_id),0)),2) AS avg_order_value
 FROM customers c
 INNER JOIN orders o
 ON c.customer_id = o.customer_id
 GROUP BY c.region
),
lagged AS(
  SELECT *,
    LAG(total_revenue) OVER(ORDER BY total_revenue DESC) AS prev_region
FROM temp
)
SELECT *,
  ROUND(
        (total_revenue/SUM(total_revenue) OVER())*100,2
        ) AS contribution_pct
FROM lagged;
-- BUSINESS INTERPRETATION:
-- The report identifies high-performing regions
-- contributing the highest revenue and customer activity.
-- Businesses can use this analysis to optimize
-- regional marketing strategies and resource allocation.

-- ===========
-- -- QUERY 4:Executive Business Snapshot Dashboard
-- ===========

-- OBJECTIVE:
-- Create a final executive business snapshot dashboard
-- summarizing overall revenue, customer activity,
-- retention performance, and top-performing business areas.
WITH temp AS(
 SELECT
   SUM(revenue) AS total_revenue,
   COUNT(DISTINCT customer_id) AS total_customers,
   COUNT(order_id) AS total_orders,
   ROUND(
        (SUM(revenue)/NULLIF(COUNT(order_id),0)),2
        ) AS avg_order_value
 FROM orders
),
regional AS(
  SELECT 
    region AS best_performing_region
  FROM (
        SELECT
          c.region,
          SUM(o.revenue) AS region_revenue
          FROM customers c
          INNER JOIN orders o
          ON c.customer_id = o.customer_id
          GROUP BY c.region
          ORDER BY SUM(o.revenue) DESC
          LIMIT 1
          ) AS temp2
),
month_revenue AS(
  SELECT
    monthly_revenue AS highest_revenue_month
    FROM (
        SELECT
          DATE_FORMAT(order_date,'%Y-%M') AS month_,
          SUM(revenue) AS monthly_revenue
          FROM orders
          GROUP BY DATE_FORMAT(order_date,'%Y-%M')
          ORDER BY SUM(revenue) DESC
          LIMIT 1
          ) AS temp3
),
repeat_cte AS(
SELECT
    ROUND(
          (COUNT(DISTINCT CASE 
                WHEN order_count>1
                THEN customer_id
                END)/
		  NULLIF(COUNT(customer_id),0))*100,2
          )AS repeat_customer_percentage
	FROM (
		SELECT
        customer_id,
        COUNT(order_date) AS order_count
        FROM orders
        GROUP BY customer_id
        ) AS temp4
)
SELECT *
FROM temp
CROSS JOIN regional
CROSS JOIN month_revenue
CROSS JOIN repeat_cte;
-- BUSINESS INTERPRETATION:
-- The dashboard provides a high-level summary of
-- overall business performance including total revenue,
-- customers, orders, repeat customer percentage,
-- best-performing region, and highest revenue month.
--
-- The strong repeat customer percentage and high revenue
-- indicate effective customer retention, successful
-- marketing campaigns, and strong customer satisfaction.
--
-- Businesses can use this executive snapshot to monitor
-- overall growth performance and support strategic
-- business decision-making.

-- ============
-- -- QUERY 5:
-- ============

-- OBJECTIVE:
-- Analyze product category performance based on
-- revenue, customer activity, order volume,
-- and revenue contribution percentage.
WITH temp AS(
 SELECT
  product_category,
  SUM(revenue) AS category_revenue,
  COUNT(order_id) AS total_orders,
  COUNT(DISTINCT customer_id) AS total_customers,
  ROUND(
       (SUM(revenue)/NULLIF(COUNT(order_id),0)),2
       ) AS avg_order_value
 FROM orders
GROUP BY product_category
),
contribution_ AS(
SELECT *,
  ROUND(
        (category_revenue/NULLIF(SUM(category_revenue) OVER(),0))*100,2
        ) AS revenue_contribution_pct
FROM temp
)
SELECT *,
  DENSE_RANK() OVER(ORDER BY revenue_contribution_pct DESC) AS performance_rnk
FROM contribution_;
-- BUSINESS INTERPRETATION:
-- The report shows that categories such as
-- Fashion and Beauty generate the highest
-- revenue and customer activity, indicating
-- strong market demand and effective marketing performance.
--
-- Categories with lower contribution percentages
-- may require targeted promotions, discounts,
-- and bundled offers to improve customer engagement
-- and revenue generation.
--
-- Product performance also depends on product nature,
-- purchase frequency, and market competition.

-- =====================================================
-- QUERY 6: CUSTOMER LIFETIME VALUE DASHBOARD
-- =====================================================

-- BUSINESS PROBLEM:
-- Businesses need to identify high-value customers
-- contributing the highest long-term revenue.
-- OBJECTIVE:
-- Analyze customer lifetime value based on
-- total revenue, total orders, and average order value.
WITH temp AS(
SELECT
    customer_id,
    COUNT(order_id) AS total_orders,
    SUM(revenue) AS lifetime_revenue,

    ROUND(
        (SUM(revenue)/NULLIF(COUNT(order_id),0)),2
    ) AS avg_order_value

FROM orders
GROUP BY customer_id
)
SELECT *,
DENSE_RANK() OVER(ORDER BY lifetime_revenue DESC)
AS customer_rank
FROM temp;
-- BUSINESS INTERPRETATION:
-- The report identifies high-value customers
-- generating the highest lifetime revenue and order activity.
-- Businesses can use this analysis for loyalty programs,
-- premium memberships, and personalized retention strategies.
